### ISSUE TITLE
Inline Clock Replacing Code Block

### ISSUE THREAD

**Issue by Willowlark** [tokenshift/obsidian-progress-clocks#8]
I have a JSON file property that I'm displaying on a page via a dataviewjs query like so 

```dataviewjs
dv.el("code", dv.current()["json"], {cls: "HyperMD-codeblock HyperMD-codeblock-begin HyperMD-codeblock-begin-bg HyperMD-codeblock-bg cm-line"})
```
When I have the plugin enabled, when I enter reading view instead of displaying the codeblock it's supposed to I get 
<img width="145" alt="image" src="https://github.com/user-attachments/assets/05a75b1c-4235-461c-87e2-1b6d2687657a">

The word clock is in the json text, is there an aggressive filter for inline clock search? Is there a way to disable inline? It's a big problem that it wipes out the entire display for me.

**Comment by tokenshift** [comment]
Yeah, something's clearly matching the code block too aggressively. Will look into it.

For my own notes/reference: I see the same thing in:
* "Reading" view only, not edit/source mode
* Only for the triple-backtick `dataviewjs` code blocks, not the single-backtick version.

I'm also seeing it sometimes render the clock at first, then switch to showing the codeblock after a few seconds; no idea what's provoking that switch, and it's pretty inconsistent.

**Comment by tokenshift** [comment]
Just pushed out v0.3.1 which should fix this (regexes for `clock` and `counter` were missing start-of-string anchors 😬). Thanks for reporting this!

**Comment by Willowlark** [comment]
I didn't expect a fix so fast! Thanks, this worked great and I love what you've done with the plugin =)
